#!/usr/bin/env bash

export DOTFILES_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export DOTFILES_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export DOTFILES_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

export DOTFILES_THEME_HOME="$DOTFILES_CONFIG_HOME/themes"
export DOTFILES_THEME_PRESETS="$DOTFILES_THEME_HOME/presets"
export DOTFILES_THEME_STATE="$DOTFILES_STATE_HOME/theme"
export DOTFILES_FONT_HOME="$DOTFILES_CONFIG_HOME/fonts"
export DOTFILES_FONT_STATE="$DOTFILES_STATE_HOME/font"
export DOTFILES_BACKGROUND_DIR="$DOTFILES_DATA_HOME/backgrounds"
export DOTFILES_BACKGROUND_STATE="$DOTFILES_STATE_HOME/background"
