set -g status-left-length 40
set -g status-right-length 500
set -g base-index 1
setw -g pane-base-index 1
set -g set-clipboard on
set -g status-position top
set -g allow-passthrough on
set -s escape-time 0

set -g default-terminal "tmux-256color"
set -as terminal-features ",foot*:RGB:sync"
set -as terminal-overrides ",foot*:Tc"

set -g status-right "#(whoami)@#h:#{s|^$HOME|~|:pane_current_path}"

source-file ~/.local/state/theme/tmux
