vim.o.termguicolors = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.softtabstop = 4
vim.o.scrolloff = 8
vim.o.wrap = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.winborder = "rounded"
vim.o.undofile = true
vim.o.undodir = vim.fn.stdpath("data") .. "/undo"
vim.o.swapfile = false
vim.o.wildignorecase = true
vim.o.wildmenu = true
vim.o.ignorecase = true
vim.o.grepprg = "rg --vimgrep"
vim.o.smartindent = true
vim.o.signcolumn = "yes"
vim.o.cursorline = true
vim.g.mapleader = " "
vim.o.wildmode = "noselect:lastused:full"
vim.g.netrw_banner = 0
vim.o.completefunc = "menuone,noselect,popup"
vim.g.vimtex_view_method = "general"
vim.g.vimtex_view_general_viewer = "evince"
vim.opt.guicursor = "n-v-c-i:block"
