vim.o.termguicolors = true
vim.o.shiftwidth = 2
vim.o.scrolloff = 8
vim.o.wrap = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.winborder = "rounded"
vim.o.undofile = true
vim.o.undodir = vim.fn.stdpath("data") .. "/undo"
vim.o.swapfile = false
vim.o.wildignorecase = true
vim.o.wildmenu = true
vim.o.ignorecase = true
vim.o.grepprg = "rg --vimgrep"
vim.o.smartindent = true
vim.o.signcolumn = "yes"
vim.o.statuscolumn = "%s%3l   "
vim.o.cursorline = true
vim.g.mapleader = " "
vim.o.wildmode = "noselect:lastused:full"
vim.g.netrw_banner = 0
vim.o.completeopt = "menuone,noselect,popup"
