bar {
    position bottom
    font pango:Iosevka Nerd Font 10
    status_padding 0
    status_edge_padding 0
    status_command dotfiles-status

    colors {
        background $base01
        statusline $base04
        separator  $base02

        #                  border    background text
        focused_workspace  $base0D   $base0D    $base00
        active_workspace   $base03   $base03    $base00
        inactive_workspace $base01   $base01    $base04
        urgent_workspace   $base08   $base08    $base00
    }
}
