exec mako
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
output * bg ~/.config/backgrounds/current fill

input type:touchpad {
    dwt enabled
    tap enabled
    middle_emulation enabled
}
