exec mako
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# fallback
output * bg #1d2021 solid_color

output * bg ~/.config/backgrounds/current fill
output HDMI-A-1 mode 1920x1080@180Hz

input type:touchpad {
    dwt enabled
    tap enabled
    middle_emulation enabled
}
