# class                 border    title_bg  text      indicator child_border
client.focused          $base0D   $base0D   $base01   $base0D   $base0D
client.focused_inactive $base01   $base01   $base04   $base01   $base01
client.unfocused        $base01   $base01   $base04   $base01   $base01
client.urgent           $base08   $base08   $base00   $base08   $base08

font $font_ui
default_border pixel 1
default_floating_border normal 1
hide_edge_borders both
floating_modifier $mod normal
