# class                 border    title_bg  text      indicator child_border
font $font_ui

client.focused          $base01   $base01   $base05   $base01   $base01
client.focused_inactive $base01   $base00   $base04   $base00   $base01
client.unfocused        $base01   $base00   $base04   $base00   $base01
client.urgent           $base08   $base08   $base00   $base08   $base08

default_border normal 1
default_floating_border normal 1
hide_edge_borders both
floating_modifier $mod normal
